export const CustomerResults = [
    {
        image: "/assets/customer-results/tasneem-mum.png",
        name: "Tasneem",
        location: "Mumbai",
        duration: "3 Months",
        desc: "My breakouts reduced significantly, my skin texture improved, and I finally stopped covering my face with makeup.",
        type: "Anti Aging",
    },
    {
        image: "/assets/customer-results/afreen-dl.png",
        name: "Afreen",
        location: "Delhi",
        duration: "3 Months",
        desc: "My breakouts reduced significantly, my skin texture improved, and I finally stopped covering my face with makeup.",
        type: "Anti Aging",
    },
    {
        image: "/assets/customer-results/ishita-blr.png",
        name: "Ishita",
        location: "Bangalore",
        duration: "3 Months",
        desc: "My breakouts reduced significantly, my skin texture improved, and I finally stopped covering my face with makeup.",
        type: "Anti Aging",
    },
    {
        image: "/assets/customer-results/tasneem-mum.png",
        name: "Tasneem",
        location: "Mumbai",
        duration: "3 Months",
        desc: "My breakouts reduced significantly, my skin texture improved, and I finally stopped covering my face with makeup.",
        type: "Acne",
    },
    {
        image: "/assets/customer-results/afreen-dl.png",
        name: "Afreen",
        location: "Delhi",
        duration: "3 Months",
        desc: "My breakouts reduced significantly, my skin texture improved, and I finally stopped covering my face with makeup.",
        type: "Acne",
    },
    {
        image: "/assets/customer-results/ishita-blr.png",
        name: "Ishita",
        location: "Bangalore",
        duration: "3 Months",
        desc: "My breakouts reduced significantly, my skin texture improved, and I finally stopped covering my face with makeup.",
        type: "Acne",
    },
    {
        image: "/assets/customer-results/tasneem-mum.png",
        name: "Tasneem",
        location: "Mumbai",
        duration: "3 Months",
        desc: "My breakouts reduced significantly, my skin texture improved, and I finally stopped covering my face with makeup.",
        type: "Hyperpigmentation",
    },
    {
        image: "/assets/customer-results/afreen-dl.png",
        name: "Afreen",
        location: "Delhi",
        duration: "3 Months",
        desc: "My breakouts reduced significantly, my skin texture improved, and I finally stopped covering my face with makeup.",
        type: "Hyperpigmentation",
    },
    {
        image: "/assets/customer-results/ishita-blr.png",
        name: "Ishita",
        location: "Bangalore",
        duration: "3 Months",
        desc: "My breakouts reduced significantly, my skin texture improved, and I finally stopped covering my face with makeup.",
        type: "Hyperpigmentation",
    },
    {
        image: "/assets/customer-results/tasneem-mum.png",
        name: "Tasneem",
        location: "Mumbai",
        duration: "3 Months",
        desc: "My breakouts reduced significantly, my skin texture improved, and I finally stopped covering my face with makeup.",
        type: "Scaring",
    },
    {
        image: "/assets/customer-results/afreen-dl.png",
        name: "Afreen",
        location: "Delhi",
        duration: "3 Months",
        desc: "My breakouts reduced significantly, my skin texture improved, and I finally stopped covering my face with makeup.",
        type: "Scaring",
    },
    {
        image: "/assets/customer-results/ishita-blr.png",
        name: "Ishita",
        location: "Bangalore",
        duration: "3 Months",
        desc: "My breakouts reduced significantly, my skin texture improved, and I finally stopped covering my face with makeup.",
        type: "Scaring",
    },
    {
        image: "/assets/customer-results/tasneem-mum.png",
        name: "Tasneem",
        location: "Mumbai",
        duration: "3 Months",
        desc: "My breakouts reduced significantly, my skin texture improved, and I finally stopped covering my face with makeup.",
        type: "Skin-glow",
    },
    {
        image: "/assets/customer-results/afreen-dl.png",
        name: "Afreen",
        location: "Delhi",
        duration: "3 Months",
        desc: "My breakouts reduced significantly, my skin texture improved, and I finally stopped covering my face with makeup.",
        type: "Skin-glow",
    },
    {
        image: "/assets/customer-results/ishita-blr.png",
        name: "Ishita",
        location: "Bangalore",
        duration: "3 Months",
        desc: "My breakouts reduced significantly, my skin texture improved, and I finally stopped covering my face with makeup.",
        type: "Skin-glow",
    },
]
